In [8]:
from scipy.stats import entropy
from collections import Counter
import math
import matplotlib
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import time
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import warnings# warning filter
import os #paths to file
warnings.filterwarnings("ignore")

In [9]:
df=pd.read_csv('/content/drive/MyDrive/machine learning/ML_FDS PROJECT/loan-train.csv')
df=df.dropna(axis=0)
df.fillna(df.mean(),inplace=True)
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [17]:
x=df[['ApplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History']].astype(float)
y=df['Loan_Status'].astype(str)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [25]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train) 
x_test = sc_x.transform(x_test)
  
print (x_train[0:100, :])

[[ 4.07326479e-01 -7.39953152e-01  2.59060651e-01  4.23021712e-01]
 [-3.34212615e-01 -4.18487057e-01  2.59060651e-01  4.23021712e-01]
 [-4.72034947e-01 -7.87577759e-01  2.59060651e-01  4.23021712e-01]
 [-8.48413542e-01  1.10550036e+00  2.59060651e-01  4.23021712e-01]
 [-1.05958686e-01  5.77590096e-02  2.59060651e-01  4.23021712e-01]
 [ 5.94142132e-01  4.03037408e-01  2.59060651e-01  4.23021712e-01]
 [-6.04362701e-01 -2.99425540e-01  2.59060651e-01  4.23021712e-01]
 [ 1.30362952e+00 -7.51859304e-01  2.59060651e-01  4.23021712e-01]
 [-8.06746326e-01 -4.66111664e-01  2.59060651e-01  4.23021712e-01]
 [ 3.24596286e+00  5.40362111e+00  2.59060651e-01  4.23021712e-01]
 [-7.19062018e-01 -9.06639275e-01  2.59060651e-01  4.23021712e-01]
 [-6.46258859e-01 -6.68516242e-01 -2.68826594e+00 -2.36394486e+00]
 [-1.65483281e-01 -1.56551720e-01  2.59060651e-01 -2.36394486e+00]
 [-5.12099579e-01 -8.94733124e-01  2.22394505e+00  4.23021712e-01]
 [-6.04362701e-01 -6.08985484e-01  2.59060651e-01  4.23021712e-01]
 [ 9.61959979e-02  1.33171724e+00  2.59060651e-01  4.23021712e-01]
 [ 4.33654665e-01 -3.11331692e-01  2.59060651e-01  4.23021712e-01]
 [-6.19472791e-01  1.64914375e-01  2.59060651e-01  4.23021712e-01]
 [-6.42366866e-01 -1.08523155e+00  2.59060651e-01  4.23021712e-01]
 [ 2.54533057e-02  2.60163588e-01  2.59060651e-01  4.23021712e-01]
 [-4.86687155e-01 -8.94733124e-01  2.59060651e-01 -2.36394486e+00]
 [-4.89663385e-01  4.03037408e-01 -7.23381546e-01 -2.36394486e+00]
 [ 2.82553770e-01  7.00691199e-01  2.59060651e-01  4.23021712e-01]
 [-4.76687350e-03  1.76820526e-01  2.59060651e-01 -2.36394486e+00]
 [-2.57746404e-01  4.26849711e-01  2.59060651e-01  4.23021712e-01]
 [-3.63745972e-01 -3.11331692e-01  2.59060651e-01  4.23021712e-01]
 [ 6.00233591e-02  3.43506650e-01  2.59060651e-01  4.23021712e-01]
 [-4.24873152e-01  1.88726678e-01  2.59060651e-01  4.23021712e-01]
 [-5.37740943e-01 -7.75671607e-01  2.59060651e-01  4.23021712e-01]
 [-1.73725148e-01 -3.70862450e-01  2.59060651e-01  4.23021712e-01]
 [-6.80599972e-01 -1.20833265e-01  2.59060651e-01  4.23021712e-01]
 [ 7.88512830e-01  1.92702482e+00  2.59060651e-01  4.23021712e-01]
 [-7.25472359e-01 -1.08927114e-01  2.59060651e-01 -2.36394486e+00]
 [-6.19472791e-01 -3.58956299e-01  2.59060651e-01 -2.36394486e+00]
 [-7.16085788e-01 -9.54263882e-01 -7.23381546e-01 -2.36394486e+00]
 [-3.17957821e-01 -2.63707085e-01  2.59060651e-01  4.23021712e-01]
 [-3.31465326e-01 -8.35202365e-01  2.59060651e-01  4.23021712e-01]
 [ 4.26099621e-01 -2.16082479e-01  2.59060651e-01  4.23021712e-01]
 [ 9.09303606e-02 -2.16082479e-01  2.59060651e-01  4.23021712e-01]
 [-4.92868556e-01 -1.44645569e-01  2.59060651e-01  4.23021712e-01]
 [-2.77206368e-01  5.77590096e-02  2.59060651e-01  4.23021712e-01]
 [-4.91494911e-01 -5.49454725e-01  2.59060651e-01  4.23021712e-01]
 [-3.01703028e-01 -1.14476231e+00 -1.70582374e+00  4.23021712e-01]
 [ 4.17080990e-02 -2.51800934e-01  2.59060651e-01  4.23021712e-01]
 [-5.10725934e-01 -8.51148104e-02  2.59060651e-01  4.23021712e-01]
 [ 2.50502064e-01  4.03037408e-01  2.59060651e-01 -2.36394486e+00]
 [-1.65483281e-01 -7.39953152e-01  2.59060651e-01  4.23021712e-01]
 [-7.37835160e-01 -2.16082479e-01  2.59060651e-01  4.23021712e-01]
 [-6.23364784e-01 -3.11331692e-01  2.59060651e-01  4.23021712e-01]
 [-4.11136707e-01  1.15312496e+00  2.59060651e-01  4.23021712e-01]
 [ 1.48623430e-01  2.01036788e+00  2.59060651e-01  4.23021712e-01]
 [ 9.20840584e-01  4.98286621e-01 -2.68826594e+00  4.23021712e-01]
 [-3.29404859e-01 -1.00188849e+00  2.59060651e-01  4.23021712e-01]
 [ 7.69281807e-01  2.73664313e+00  2.59060651e-01 -2.36394486e+00]
 [-3.90532040e-01 -7.87577759e-01  2.59060651e-01  4.23021712e-01]
 [-1.02066693e-01 -2.51800934e-01  2.59060651e-01  4.23021712e-01]
 [-2.22718469e-01  1.64914375e-01  2.59060651e-01 -2.36394486e+00]
 [ 2.21916359e+00  1.14121881e+00  2.59060651e-01 -2.36394486e+00]
 [ 2.21939253e+00  1.83177561e+00  2.59060651e-01  4.23021712e-01]
 [ 8.83981123e-01  4.62568166e-01  2.59060651e-01  4.23021712e-01]
 [-4.70661303e-01  2.83975891e-01  2.59060651e-01  4.23021712e-01]
 [-8.00107044e-01 -1.09713770e+00  2.59060651e-01  4.23021712e-01]
 [-6.24738428e-01  6.96651612e-02  2.59060651e-01  4.23021712e-01]
 [-4.88289740e-01 -1.08927114e-01  2.59060651e-01  4.23021712e-01]
 [-7.27074944e-01 -9.06639275e-01 -2.68826594e+00  4.23021712e-01]
 [ 7.94268237e+00  5.40362111e+00 -2.68826594e+00 -2.36394486e+00]
 [-2.20658002e-01 -2.63707085e-01  2.59060651e-01  4.23021712e-01]
 [-8.62607869e-01 -1.38288534e+00  2.59060651e-01  4.23021712e-01]
 [-2.22718469e-01 -4.30393209e-01  2.59060651e-01  4.23021712e-01]
 [ 2.08376966e-01 -1.56551720e-01  2.59060651e-01  4.23021712e-01]
 [ 9.19695881e-01  2.78426774e+00 -7.23381546e-01  4.23021712e-01]
 [-7.46534908e-01 -5.37548574e-01  2.59060651e-01  4.23021712e-01]
 [ 1.70372801e-01 -3.11331692e-01 -2.68826594e+00  4.23021712e-01]
 [-5.92686723e-01 -1.02570079e+00 -2.68826594e+00  4.23021712e-01]
 [-8.90170700e-02 -1.92270175e-01  2.59060651e-01 -2.36394486e+00]
 [-2.60722634e-01  1.41102071e-01  2.59060651e-01  4.23021712e-01]
 [-2.34623388e-01 -5.49454725e-01  2.59060651e-01  4.23021712e-01]
 [ 9.62049920e-01  4.86380469e-01  2.59060651e-01  4.23021712e-01]
 [-3.41538719e-01 -2.63707085e-01 -7.23381546e-01  4.23021712e-01]
 [-5.24462379e-01  8.15713129e-02  2.59060651e-01  4.23021712e-01]
 [ 4.20376102e-01 -9.70209621e-02  2.59060651e-01  4.23021712e-01]
 [ 9.20750643e-02  4.86380469e-01  2.59060651e-01  4.23021712e-01]
 [ 7.85675600e-02 -1.21619922e+00  2.59060651e-01  4.23021712e-01]
 [-2.34165506e-01  3.07788195e-01 -4.26017346e+00  4.23021712e-01]
 [-6.47174622e-01 -1.03760694e+00  2.59060651e-01  4.23021712e-01]
 [ 1.17945369e-01 -2.55840521e-02  2.59060651e-01  4.23021712e-01]
 [-4.44104175e-01 -1.32739417e-01  2.59060651e-01  4.23021712e-01]
 [-5.92457782e-01 -9.06639275e-01  2.59060651e-01  4.23021712e-01]
 [-7.40582449e-01 -6.20891635e-01  2.22394505e+00  4.23021712e-01]
 [-3.56190927e-01  3.55412801e-01  2.59060651e-01  4.23021712e-01]
 [ 9.09303606e-02 -1.92270175e-01  2.59060651e-01  4.23021712e-01]
 [ 2.50556847e+00  5.45911228e-01  2.59060651e-01 -2.36394486e+00]
 [-2.96895272e-01 -3.58956299e-01  2.59060651e-01  4.23021712e-01]
 [-6.42366866e-01 -5.13736270e-01  2.59060651e-01  4.23021712e-01]
 [ 1.16992812e+00  4.86380469e-01  2.59060651e-01 -2.36394486e+00]
 [ 1.53257027e+00  4.16538133e+00  2.59060651e-01  4.23021712e-01]
 [ 2.79174441e+00  3.02239077e+00  2.59060651e-01  4.23021712e-01]
 [-6.98915232e-01 -4.30393209e-01  2.59060651e-01  4.23021712e-01]
 [-5.97036597e-01 -2.87519389e-01  2.59060651e-01  4.23021712e-01]
 [-1.40757680e-01 -5.49454725e-01  2.59060651e-01  4.23021712e-01]]

In [26]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [27]:
y_pred = classifier.predict(x_test)

In [28]:

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix :
 [[18 31]
 [ 0 95]]

In [29]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_test, y_pred)
print ("Accuracy : ",100*a )

Accuracy :  78.47222222222221